# Jobs run on pull request
name: Pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format Rust Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup show
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    name: Lint Rust Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Install toolchain
        run: rustup show
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "check"
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- --deny warnings -W clippy::cargo -W clippy::dbg_macro -A clippy::cargo_common_metadata
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: lint

  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "dependencies"
      - name: Install toolchain
        run:  rustup toolchain install nightly
      - name: Install udeps
        run: cargo install cargo-udeps --locked
      - name: Run udeps
        run: cargo +nightly udeps


  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup show
      - name: Install nextest
        run: "curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin"

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "test"
          cache-on-failure: true
      - name: Compile for tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --workspace --verbose
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --workspace --verbose
      - name: Run doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup show
      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "doc"
      - name: Run doc command
        uses: actions-rs/cargo@v1
        with:
          command: doc

